version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.16
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: "Install"
          command: npm install
      - run:
          name: "Lint code"
          command: npm run lint
      - run:
          name: "Test code"
          command: npm test
      - run:
          name: "Build"
          command: npm run-script build
      - aws-s3/sync:
          arguments: |
              --acl public-read \
              --cache-control "max-age=86400"
          from: build
          overwrite: true
          to: s3://sandrobraidotti.com
