version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.16
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: "Install"
          command: npm install
      - run:
          name: "Lint code"
          command: npm run lint
      - run:
          name: "Test code"
          command: npm test
      - run:
          name: "Build"
          command: npm build
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          from: bucket
          overwrite: true
          to: $S3_BUCKET_NAME
      - aws-s3/copy:
          from: build
          to: $S3_BUCKET_NAME
